package com.ddzhuan.manage.model.jumi.product;

import java.io.Serializable;
import java.util.Date;

public class JmGoodsManuFatory implements Serializable {

    private static final long serialVersionUID = 8058823009166098931L;

    private Long id;

    /**
     * 生产厂家名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LS_JM_GOODSMANUFACTOR_T.NAME
     */
    private String name;

    /**
     * 生产厂家地址
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LS_JM_GOODSMANUFACTOR_T.ADDRESS
     *
     * @mbg.generated Fri Dec 27 11:00:13 CST 2019
     */
    private String address;

    /**
     * 简介
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LS_JM_GOODSMANUFACTOR_T.DESCRIPTION
     *
     * @mbg.generated Fri Dec 27 11:00:13 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LS_JM_GOODSMANUFACTOR_T.CREATETIME
     *
     * @mbg.generated Fri Dec 27 11:00:13 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LS_JM_GOODSMANUFACTOR_T.UPDATETIME
     *
     * @mbg.generated Fri Dec 27 11:00:13 CST 2019
     */
    private Date updatetime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public Date getUpdatetime() {
        return updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}